version: "3.3"
services:
  db:
    container_name: timetrackr_db
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: timetrackr
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  service:
    container_name: timetrackr_backend
    build: dev-environment/service/
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: timetrackr
      MYSQL_USERNAME: root
      MYSQL_PASSWORD:
    ports:
      - 8080:80
    tty: true
    volumes:
      - ./service:/var/www/html
    depends_on:
      - db
  ui:
    container_name: timetrackr_ui
    build: dev-environment/ui/
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./ui:/app
